DOMAIN = "caldaia_smart"
CONF_NAME = "name"
CONF_TEMP_ACS = "temp_acs"
CONF_TEMP_ACF = "temp_acf"
CONF_TEMP_MANDATA = "temp_mandata"
CONF_TEMP_RITORNO = "temp_ritorno"
CONF_TEMP_FUMI = "temp_fumi"
CONF_CONSUMO_ELETTRICO = "consumo_elettrico"
